-- m10_newgame.lua — walk through the intro into a new game, then profile it.
--
-- Two phases. Until MainLoop starts turning over, green is pulsed (6 frames
-- down, 24 up — the engine waits for a release after every press) because green
-- is F_SPACE, which is both "skip this pause" and the menu's confirm, and
-- "New game" is the entry already selected. Once CmptFrame moves, the button is
-- let go and the stick is held instead: a standing-still LBA repaints nothing
-- at all, so profiling an idle scene measures zero and says nothing.
--
-- What comes out is the pair that matters for phase E — how many game frames
-- per second the engine completes, and how much of the screen each one
-- repaints. LBA's frame is incremental (FLIPBOX.C pushes dirty rectangles), so
-- neither number means much without the other.
--
-- Symbols come from build/syms.lua (HSLBA_SYMS), regenerated by every build.

local S = dofile(assert(os.getenv("HSLBA_SYMS"), "set HSLBA_SYMS to build/syms.lua"))

local TRACE = 0xa0ef0000
local CON   = TRACE + 0x1000

local mem, ports, frame, con_read = nil, nil, 0, 0
local last = {}
local pressing = true

local PRESS, PERIOD = 6, 30

-- Analog Y above centre is "up" — see the PORT_REVERSE note in src/input.c.
local WALK_Y = 0xe0

-- CmptFrame (PERSO.C, one per MainLoop iteration) is a UWORD and laps.
local cf_hi, cf_prev = 0, nil
local function frames()
  local v = mem:read_u16(S["CmptFrame"])
  if cf_prev and v < cf_prev then cf_hi = cf_hi + 0x10000 end
  cf_prev = v
  return cf_hi + v
end

local function drain()
  if mem:read_u32(CON) ~= 0xC04501E1 then return end
  local total = mem:read_u32(CON + 4)
  local size = 0x4000 - 16
  if total - con_read > size then con_read = total - size end
  local out = {}
  while con_read < total do
    out[#out + 1] = string.char(mem:read_u8(CON + 16 + (con_read % size)))
    con_read = con_read + 1
  end
  if #out > 0 then io.write(table.concat(out)); io.flush() end
end

local function field(port, name)
  local p = ports[port]
  return p and p.fields[name] or nil
end

_G.m10 = emu.add_machine_frame_notifier(function()
  frame = frame + 1
  if not mem then
    mem = manager.machine.devices[":maincpu"].spaces["program"]
    ports = manager.machine.ioport.ports
  end

  local gf = frames()

  if pressing and gf > 2 then
    pressing = false
    print(string.format("[%6.2fs] MainLoop running (CmptFrame=%d) — walking", emu.time(), gf))
  end

  local green = field(":ctrl0:IN.1", "Green")
  if green then
    green:set_value((pressing and (frame % PERIOD) < PRESS) and 1 or 0)
  end
  local ay = field(":ctrl0:IN.2", "Analog Y")
  if ay then
    ay:set_value(pressing and 0x7f or WALK_Y)
  end

  drain()

  if frame % 300 == 0 then
    local t  = mem:read_u32(S["TimerRef"])
    local rc = mem:read_u32(S["PORT_rects"])
    local px = mem:read_u32(S["PORT_pixels"])
    local dt = emu.time() - (last.time or 0)
    local df = gf - (last.gf or gf)

    -- Rates per second of emulated time, not per game frame: CmptFrame is not
    -- trustworthy read from outside, and the question is only whether the
    -- frame regulator bites. Screen-loads per second answers that on its own.
    local drc = rc - (last.rc or rc)
    local dpx = px - (last.px or px)

    print(string.format(
      "[%6.2fs] tick %.1f Hz | %.0f rects/s  %.0f px/s = %.2f screens/s  (CmptFrame %+d) cube=%d",
      emu.time(),
      (t - (last.t or t)) / dt,
      drc / dt, dpx / dt, (dpx / dt) / (320 * 240),
      df, mem:read_u8(S["NumCube"])))

    last.t, last.time, last.gf, last.rc, last.px = t, emu.time(), gf, rc, px
    manager.machine.video:snapshot()
  end

  if frame > tonumber(os.getenv("HSLBA_FRAMES") or "3600") then
    manager.machine:exit()
  end
end)
